version: '3.8'
services:
  api:
    container_name: app
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: database
    image: mysql:latest
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - .env
