###Request users data for testing
GET http://localhost:5500/users

###Register an user
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "email": "timi@email.com",
    "password": "password15"
}

###Register a second user
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "email": "marcel1994@coolmail.it",
    "password": "cool1234567890"
}

###Register real email to test confirmation
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "email": "tmierlut@gmail.com",
    "password": "manancmere15"
}

###Register with no entry for password
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "email": "marcel1994@coolmail.it",
    "password": ""
}

###Register an invalid email
POST http://localhost:5500/users/register
Content-Type: application/json

{
    "email": "elena",
    "password": "ParolaOriginala"
}

###Login timi
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "email": "timi@email.com",
    "password": "password15"
}

###Login marcel
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "email": "marcel1994@coolmail.it",
    "password": "cool1234567890"
}

###Incorrect password login
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "email": "timi@email.com",
    "password": "pass"
}
